sudo: required
services:
  - docker

before_install:
  - docker build -t priyojit/complex-demo-react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true priyojit/complex-demo-react-test npm run test -- --coverage

after_success:
  - docker build -t priyo153/client ./client
  - docker build -t priyo153/server ./server
  - docker build -t priyo153/worker ./worker
  - docker build -t priyo153/nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push priyo153/client
  - docker push priyo153/server
  - docker push priyo153/worker
  - docker push priyo153/nginx
